// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBgupfk1H2vrhqzNH6J3WOyDrm9SR1iMFw',
    appId: '1:332275413352:web:9f4d84146482cb684226dd',
    messagingSenderId: '332275413352',
    projectId: 'point-marketing-18d63',
    authDomain: 'point-marketing-18d63.firebaseapp.com',
    storageBucket: 'point-marketing-18d63.appspot.com',
    measurementId: 'G-ZYF7P2XQHC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAMMSBXBSp1trUZbcmKWLMeuyf9oCe9Bgo',
    appId: '1:332275413352:android:c4116e2d639d70f04226dd',
    messagingSenderId: '332275413352',
    projectId: 'point-marketing-18d63',
    storageBucket: 'point-marketing-18d63.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA9xalyx0W_3WHsck4x8_rv9Oa9tsvzZRE',
    appId: '1:332275413352:ios:9107d962534c38c94226dd',
    messagingSenderId: '332275413352',
    projectId: 'point-marketing-18d63',
    storageBucket: 'point-marketing-18d63.appspot.com',
    iosBundleId: 'com.example.marketStatistic',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA9xalyx0W_3WHsck4x8_rv9Oa9tsvzZRE',
    appId: '1:332275413352:ios:152530d99fbf94b64226dd',
    messagingSenderId: '332275413352',
    projectId: 'point-marketing-18d63',
    storageBucket: 'point-marketing-18d63.appspot.com',
    iosBundleId: 'com.example.marketStatistic.RunnerTests',
  );
}
